name: Generate CSV-W from csv upload to repository.

on:
  push:
    branches:
      #- main
      - action-publish

jobs:
  generate_csvw_from_csv_upload:
    name: Generate CSV-W from csv upload
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install csvcubed
        run: pip install csvcubed

      - name: Verify csvcubed installation
        run: csvcubed version

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: View working directory
        run: ls -la $GITHUB_WORKSPACE

      - name: Configure git
        run: |
          git config --global user.name "CSV-W from csv upload generator"
          git pull

      - name: Get all added/changed/removed files inside csv folder
        id: get-added-changed-removed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"

      - name: Build and inspect new files
        id: build-and-inspect-inputs
        run: |
          input_files=${{steps.get-added-changed-removed-files.outputs.added_modified}}
          bash .github/workflows/scripts/build_and_inspect_inputs.sh $input_files

      - name: Process all deleted files inside csv folder
        id: process-deleted-files
        run: |
          deleted_files=${{steps.get-added-changed-removed-files.outputs.removed}}
          bash .github/workflows/scripts/handle_deleted_files.sh $deleted_files

      - name: Commit generated CSV-Ws and logs to the repository
        if: ${{ fromJSON(steps.build-and-inspect-inputs.outputs.has_outputs) == true }}
        run: |
          echo $'\nCommitting CSV-Ws\n'
          git add out/
          git commit -m "CSV-Ws generated from csv upload - $(date +'%d-%m-%Y at %H:%M:%S')"
          git push

      - name: Publish CSV-Ws and logs to artefacts
        if: ${{ fromJSON(steps.build-and-inspect-inputs.outputs.has_outputs) == true }}
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: out

      - name: Publish CSV-Ws and logs to GitHub Pages
        if: ${{ fromJSON(steps.build-and-inspect-inputs.outputs.has_outputs) == true }}
        run: |
          echo $'\n'
          echo "Publishing to GitHub Pages"
          git checkout -b gh-pages
          rm -r LICENSE
          rm -r README.md
          rm -r .github/workflows

          repo_name=${GITHUB_REPOSITORY#*/}    
          username=${GITHUB_REPOSITORY_OWNER}
          commit_id=${GITHUB_SHA}      
          mapfile -d ',' -t out_files < <(printf '%s,' $(find . -type f -path '*out/*'))
          processed_out_files=$(printf ",%s" "${out_files[@]}")

          touch .nojekyll
          touch index.html

          cat > index.html <<EOL
          <!doctype html>
          <html>
            <head>
            </head>
            <body>
              <h3>CSV-Ws generated are as below. The latest commit id is ${commit_id}.</h3>
              <div id="files-container"></div>
              <script type="text/javascript">
                var html_str = "<ul>";
                var files = "${processed_out_files}".split(',');
                files.shift()
                files.sort()
                files.forEach(function(file) {
                  file = file.replace("./","")
                  link = "https://${username}.github.io/${repo_name}/"+file
                  html_str += "<li>"+"<a href='"+ link + "'>"+file+"</a></li>";
                });
                html_str += "</ul>";
                document.getElementById("files-container").innerHTML = html_str;
              </script>
            </body>
          </html>
          EOL

          git add .nojekyll
          git add index.html
          git commit -a -m "Updating outputs in GitHub Pages - $(date +'%d-%m-%Y at %H:%M:%S')"
          git push --set-upstream origin gh-pages -f
