name: Generate CSV-W from csv upload to repository.

on:
  push:
    branches:
      - main
    paths:
      - "csv/**"
      - "*.csv"
      - "*.json"

jobs:
  generate_csvw_from_csv_upload:
    name: Generate CSV-W from csv upload
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install csvcubed
        run: pip install csvcubed

      - name: Verify csvcubed installation
        run: csvcubed version

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: View working directory
        run: ls -la $GITHUB_WORKSPACE

      - name: Get all the changes files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"

      - name: List all the changes files
        run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.changed-files.outputs.added_modified }}')

          for file in "${added_modified_files[@]}"; do
            echo "Processing changed file ${file}"  
            file_name="${file%.*}"
            file_extension="${file##*.}"

            if [[ "$file_extension" == "csv" ]]; then
              echo "Changed file is supported"
              csv_file=${file}

              for file_secondary in "${added_modified_files[@]}"; do
                if [[ "${file_secondary%.*}.csv.json" == "${file_name}.csv.json" ]]; then
                  config_file="${file}.json"
                  echo "Config for ${csv_file} is available: ${config_file}"

                  echo $'Building CSV-Ws'
                  csvcubed build ${csv_file} -c ${config_file}
                  ls out/
                else
                  echo "Config for ${csv_file} is not available"

                  echo $'Building CSV-Ws'
                  csvcubed build ${csv_file}
                  ls out/
                fi
              done
            else
              echo "Changed file is not supported"
            fi
          done

      # TODO: Change this to upload to artifacts: upload-artifact@v*
      - name: Commit generated CSV-Ws to the repository
        run: |
          echo $'\nCommitting CSV-Ws\n'
          git config --global user.name "CSV-W from csv upload generator"
          git add out/
          git commit -m "CSV-Ws generated from csv upload - $(date +'%d-%m-%Y at %H:%M:%S')"
          git push

      - name: Publish CSV-Ws and logs to GitHub Pages
        # TODO: Publish generated CSV-Ws and logs to GitHub pages.
        run: |
          echo $'\nPublishing CSV-Ws to GitHub Pages\n'
