name: Generate CSV-W from csv upload to repository.

on:
  push:
    branches:
      - main

jobs:
  generate_csvw_from_csv_upload:
    name: Generate CSV-W from csv upload
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install csvcubed
        run: pip install csvcubed
      
      - name: Verify csvcubed installation
        run: csvcubed -h # Ideally, this should be csvcubed -v which we will have to implement into the csvcubed project.
      
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: View working directory
        run: ls -la $GITHUB_WORKSPACE
      
      - name: List csvs and config jsons in repository
        run: |
          cd csv
          ls
      
      - name: Build a CSV-W from csv
        run: |
          csvcubed build csv/sweden_at_eurovision_no_missing.csv
          ls out/
      
      - name: Build a CSV-W from csv and config.json
        run: |
          csvcubed build csv/sweden_at_eurovision_no_missing.csv -c csv/sweden_at_eurovision_no_missing.csv.json
          ls out/

      - name: Commit generated CSV-Ws to the repository
        run: |
          git config --global user.name "CSV-W from csv upload generator"
          git add out/
          git commit -m "CSV-Ws generated from csv upload - $(date +'%Y-%m-%dT%H:%M:%S')"
