name: Generates GitHub Pages index with csvcubed build command output urls.

on:
  push:
    branches:
<<<<<<< Updated upstream
      - gh-pages
=======
      - 'gh-pages'
    paths:
      - 'out/**'
>>>>>>> Stashed changes

jobs:
  generate_gh_pages_index:
    name: Generate GitHub Pages index
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          fetch-depth: 0
      
      - name: View working directory
        run: ls -la $GITHUB_WORKSPACE